[project]
name = "thematic-analysis-model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ckol", email = "christopher.kollar@ucalgary.ca" }
]
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "bertopic>=0.17.4",
    "httpx>=0.28.1",
    "lancedb>=0.33.0",
    "sentence-transformers>=5.5.1",
    "xxhash>=3.7.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
start = "thematic_analysis_model.main:main"